CREATE DATABASE Groupomania CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER 'adminOC' IDENTIFIED BY 'devweb';
GRANT ALL ON Groupomania.* TO 'adminOC';

USE Groupomania;

CREATE TABLE User (
	userID SMALLINT UNSIGNED AUTO_INCREMENT,
	firstName VARCHAR(30) NOT NULL,
	lastName VARCHAR(30) NOT NULL,
	email VARCHAR(60) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	avatarUrl VARCHAR(150) NOT NULL DEFAULT 'http://localhost:3000/images/avatar.png',
	dateCreation DATETIME NOT NULL,
	PRIMARY KEY (userID)
)
ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Post (
	postID MEDIUMINT UNSIGNED AUTO_INCREMENT,
	userID SMALLINT UNSIGNED NOT NULL,
	gifUrl VARCHAR(150),
	postTitle VARCHAR(150) NOT NULL,
	postText TEXT,
	claps SMALLINT,
	dateSend DATETIME NOT NULL,
	PRIMARY KEY (postID),
	FOREIGN KEY (userID) REFERENCES User (userID)
)
ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Comment (
	commentID INT UNSIGNED AUTO_INCREMENT,
	postID MEDIUMINT UNSIGNED NOT NULL,
	userID SMALLINT UNSIGNED NOT NULL,
	commentText TEXT NOT NULL,
	dateSend DATETIME NOT NULL,
	PRIMARY KEY (commentID),
	UNIQUE INDEX index_postID_comID (postID, commentID),
	FOREIGN KEY (userID) REFERENCES User (userID),
	FOREIGN KEY (postID) REFERENCES Post (postID)
)
ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

